#!/usr/bin/bash

#D brightness
#D Change thinkpad monitor brightness (thinkpad only script)
#D just pass a value between 0 - 500
#D shows the current brightness if no value is passed
#D This script needs to be run with sudo

if [ -z $1 ]; then
  cat /sys/class/backlight/intel_backlight/brightness
  exit
fi

echo $1
echo $1 > /sys/class/backlight/intel_backlight/brightness
