#!/home/mmc/.config/nvm/versions/node/v12.16.1/bin/node

const cron = require('node-cron')
const fs = require('fs')
const { exec } = require('child_process')

const checkBatteryCapacity = (bat) => {
  batCapacity = fs.readFileSync(`/sys/class/power_supply/${bat}/capacity`, 'utf8')
  batStatus = fs.readFileSync(`/sys/class/power_supply/${bat}/status`, 'utf8')
  batCapacity = parseInt(batCapacity.replace('\n', ''))
  return {
    capacity: batCapacity,
    status: batStatus
  }
}

cron.schedule('* * * * * *', () => {
  let bat1 = checkBatteryCapacity('BAT0') 
  let bat2 = checkBatteryCapacity('BAT1') 
  if (bat1.capacity < 30 && bat2.capacity < 30) {
    if(bat1.status !== 'Charging\n' && bat2.status !== 'Charging\n') {
      exec('dunstify "LOW BATTERY!!!"')
    }
  }
})

// asdfaskldj
