#!/usr/bin/bash

SELECTION=$(du -h ./ | grep [0-9]M | fzf | awk '{ print $2 }')

while true; do
    read -p "Do you really want to delete $SELECTION y/n? " yn
    case $yn in
        [Yy]* ) rm -rf $SELECTION; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer y or n.";;
    esac
done
