#!/usr/bin/bash

#D reloadkeyboard
#D reload your keyboard configuration
#D usefull when you plug a different keyboard in your computer
#D 

[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap
[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources

# set key input rate
xset r rate 200 25
