#!/usr/bin/bash

#D screen 
#D list all available arandr screen layouts 
#D arandr needs to be installed
#D

OPTS=$(ls ~/.screenlayout/)
SELECTION=$(echo -e "$OPTS" | fzf)
bash ~/.screenlayout/$SELECTION
feh --bg-scale ~/.config/i3/background.jpg
